export const ERROR_CODES = {
  // State Machine
  STATE_TRANSITION_DENIED: 'STATE_TRANSITION_DENIED',
  STATE_INVALID_FROM: 'STATE_INVALID_FROM',
  STATE_INVALID_TO: 'STATE_INVALID_TO',
  STATE_GATE_FAILED: 'STATE_GATE_FAILED',
  // Registry
  REGISTRY_NOT_FOUND: 'REGISTRY_NOT_FOUND',
  REGISTRY_INVALID: 'REGISTRY_INVALID',
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  // Search
  SEARCH_EMPTY_QUERY: 'SEARCH_EMPTY_QUERY',
  SEARCH_TIMEOUT: 'SEARCH_TIMEOUT',
  // Prompts
  PROMPT_BUILD_FAILED: 'PROMPT_BUILD_FAILED',
  PROMPT_LLM_ERROR: 'PROMPT_LLM_ERROR',
  // Secrets
  SECRET_NOT_FOUND: 'SECRET_NOT_FOUND',
  SECRET_INVALID: 'SECRET_INVALID',
  SECRET_ENCRYPT_FAILED: 'SECRET_ENCRYPT_FAILED',
  // DevOps
  DEPLOY_FAILED: 'DEPLOY_FAILED',
  SERVICE_DISCONNECTED: 'SERVICE_DISCONNECTED',
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
